---
title: "Linear Models"
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)
library(modelr)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Examples
```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

#### Introduce broom

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(boro = neighbourhood_group,
         neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)

fit = lm(price ~ stars + boro, data = nyc_airbnb)

```

look at some summaries
```{r, results = FALSE}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)

```

look at a better summaries by broom

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term,"^boro", "Boro: ")) %>% # replace start with boro to Boro:
  knitr::kable(digits = 3)
```

More in broom

```{r}
fit %>% 
  broom::glance() %>% 
  select(r.squared, adj.r.squared)
```
Be careful with factors...

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(boro = fct_infreq(boro),
         room_type = fct_infreq(room_type))
fit = lm(price ~ stars + boro, data = nyc_airbnb)
fit %>% broom::tidy()
```

#### Diagnostics
```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()

nyc_airbnb %>% 
modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()


nyc_airbnb %>% 
modelr::add_predictions(fit) %>% View()

nyc_airbnb %>% 
modelr::add_predictions(fit) %>% 
  ggplot(aes(x = stars, y = pred, color = boro)) +
  geom_point()

```

#### Testing

```{r}
fit %>% 
  broom::tidy()
```

compare nested models.

```{r}
fit_null = lm(price ~ stars + boro, data = nyc_airbnb)
fit_alt = lm(price ~ stars + boro + room_type, data = nyc_airbnb)
anova(fit_null, fit_alt) %>% 
  broom::tidy()

```

#### Nested data

```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

Nesting and then fitting

```{r}
# stratify analysis
nest_lm_res =
  nyc_airbnb %>% 
  group_by(boro) %>% 
  nest() %>%
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)), # map in each group
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% # get models for each boro
  unnest()
# but those models are separate have no interaction
```

look at the neighborhood in Manhattan

```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(boro == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  group_by(neighborhood) %>% 
  nest() %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest()
```

View results

```{r}
manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 80, hjust = 1)) +
  facet_grid(~term)
```

#### Binary outcomes

```{r}
baltimore_df = 
  read_csv("data/homicide-data.csv") %>% 
  filter(city == "Baltimore") %>% 
  mutate(resolved = as.numeric(disposition == "Closed by arrest"),
         victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White")) %>% 
  select(resolved, victim_age, victim_race, victim_sex)
```

```{r}
fit_logistic = 
  baltimore_df %>% 
  glm(resolved ~ victim_age + victim_race, data = ., family = binomial()) 
# telling that the model you are model is binomial family
summary(fit_logistic)
```

```{r}
fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = boot::inv.logit(estimate)) %>% 
  knitr::kable(digits = 3)
# not a very good plot but nice enough for exploring the data 
baltimore_df %>% 
  ggplot(aes(x = victim_age, y = resolved)) + geom_point() + geom_smooth()
```





